/*
 * hal/sel4/sel4_pd_fs.c — seL4 Microkit Protection Domain: Filesystem
 * =====================================================================
 * Runs services/fs/init.nx in isolation.
 *
 * This PD has NO direct UART access.  All output goes through the
 * log MR (g_log_mr) → sel4_uart_daemon_puts() → microkit_notify(SEL4_CH_LOG).
 *
 * IPC model:
 *   - Root sends a request by writing into g_req_mr and notifying CH_FS.
 *   - This PD's notified() reads g_req_mr (a NEXS Value → KernelMsg),
 *     dispatches it, writes the reply into g_rep_mr, and notifies CH_BACK_FS.
 *
 * Memory regions (vaddr must match nexs_*arch*.system XML):
 *   SEL4_FS_REQ_VADDR  0x6_0000_0000  — root→fs  request MR (r)
 *   SEL4_FS_REP_VADDR  0x6_0001_0000  — fs→root  reply   MR (rw)
 *   SEL4_FS_LOG_VADDR  0x6_0002_0000  — fs→root  log     MR (rw)
 *
 * ONLY compiled when NEXS_SEL4 is defined.
 */

#ifdef NEXS_SEL4

#include "sel4_ipc_bridge.h"
#include "sel4_uart_daemon.c"   /* pulls in sel4_uart_daemon_puts() inline */
#include "../../runtime/include/nexs_runtime.h"
#include "../../lang/include/nexs_eval.h"
#include "../../kernel/include/nexs_msg.h"
#include "../../kernel/include/nexs_vfs.h"
#include "../../registry/include/nexs_registry.h"
#include "../../hal/include/nexs_hal.h"
#include <microkit.h>
#include <string.h>

/* MR virtual addresses — must match the .system XML */
#define SEL4_FS_REQ_VADDR  0x30000000UL
#define SEL4_FS_REP_VADDR  0x30010000UL
#define SEL4_FS_LOG_VADDR  0x30020000UL

static NexsMR    *g_req_mr  = (NexsMR    *)SEL4_FS_REQ_VADDR;
static NexsMR    *g_rep_mr  = (NexsMR    *)SEL4_FS_REP_VADDR;
static NexsLogMR *g_log_mr  = (NexsLogMR *)SEL4_FS_LOG_VADDR;

/* Embedded FS service script — generated by:
 *   ./nexs --codegen services/fs/init.nx -o build/sel4-multikernel/nexs_embed_fs.c
 * Declared weak so the PD links even without the codegen step. */
extern const char nexs_fs_script_src[] __attribute__((weak));

/* =========================================================
   UART SHIM: redirect nexs_hal_print → log MR for this PD
   =========================================================
   Service PDs override nexs_hal_print via a weak alias so that
   existing runtime code (eval, builtins) naturally routes all
   print output through the daemon without any source changes.
   ========================================================= */

void nexs_hal_print(const char *s) {
    sel4_uart_daemon_puts(g_log_mr, s, SEL4_CH_LOG_FS);
}

void nexs_hal_putc(char c) {
    char tmp[2] = { c, '\0' };
    sel4_uart_daemon_puts(g_log_mr, tmp, SEL4_CH_LOG_FS);
}

int nexs_hal_getc(void) { return -1; } /* FS PD has no console input */

/* =========================================================
   init — called once by Microkit after all PDs are loaded
   ========================================================= */

void init(void) {
    nexs_runtime_init();

    /* Register VFS subsystem for this PD */
    vfs_init();
    reg_ipc_init_queue("/services/fs/inbox", 64);

    /* Log PD boot via daemon */
    sel4_uart_daemon_puts(g_log_mr, "[nexs_fs] PD initialized\n", SEL4_CH_LOG_FS);

    /* Execute the embedded FS service script */
    if (nexs_fs_script_src && nexs_fs_script_src[0]) {
        EvalCtx ctx;
        eval_ctx_init(&ctx);
        ctx.out = NULL;
        EvalResult r = eval_str(&ctx, nexs_fs_script_src);
        if (r.sig == CTRL_ERR)
            sel4_uart_daemon_puts(g_log_mr, "[nexs_fs] script error\n", SEL4_CH_LOG_FS);
        val_free(&r.ret_val);
    }
}

/* =========================================================
   notified — IPC handler
   ========================================================= */

void notified(microkit_channel ch) {
    if (ch == SEL4_CH_FS) {
        /* Read request from root */
        Value req = val_nil();
        if (sel4_bridge_read(g_req_mr, &req) != 0) return;

        KernelMsg km;
        Value reply;
        if (kmsg_decode(&req, &km) == 0) {
            reply = kmsg_handle(&km);
        } else {
            reply = val_err(1, "fs: bad kmsg");
        }
        val_free(&req);

        /* Write reply and notify root */
        sel4_bridge_write(g_rep_mr, &reply);
        val_free(&reply);
        microkit_notify(SEL4_CH_BACK_FS);
    }
}

#endif /* NEXS_SEL4 */
